version: '2'
services:
  mariadb:
    image: schmunk42/mariadb-example-databases
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secretadmin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secretadmin
      - INSTALL_SAKILA=1
      - INSTALL_WORLD=1
    networks:
      - ${NETWORK_NAME}
